baseURL = "https://fillthegap.github.io"
languageCode = "en-us"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"

# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]
  [params.logo]
    text1 = "Alireza"
    text2 = "Baloochi"

  [params.footer]
      copyright = "This site is available under MIT License."
      [params.footer.radity_logo]
        x = "img/general/github.png"
        _2x = "img/general/githubx2.png"
        alt = "Github"
